# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a29a000a88a7fee9916b951a7d8975d82cad26b15234853a2ab3fbbdd502e677451ba83aa2ac69d04e6075b6199b25532f6066716d33f539963a6693b2f5af05

test:
  secret_key_base: ee0789c7bf7a2e0817e0b1fce98c4ef3fe27a8e62a489509b559497f0410d22cd390d3e7059814a5b1ed81e5bbd9b66e98f4bbdfd6a436cfc2eb6a3d6f536e6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
